flood_fill: flood_fill_driver.o flood_fill.o
	c99 -o flood_fill flood_fill_driver.o flood_fill.o

flood_fill.o: flood_fill.c
	c99 -c flood_fill.c

flood_fill_driver.o: flood_fill_driver.c
	c99 -c flood_fill_driver.c